### ISSUE TITLE
Hello World Site - Flask

### ISSUE THREAD

**Issue by richc117** [Sin-Aman/Scorehub#2]
## Overview
Create a hello world version of your project. Chapter 7 in the book

**Requirements for Part B**
1.  Submit repo address
2. Professor will git clone your repo
3. Details for the professor on how to create a virtual environment (What does the professor need to type into terminal to get the hello world site running?)
4. Include a requirements .txt file (pip module, etc. Generate the the requirements for your project by running `pip freeze > requirements.txt`
5. Instructions to have the professor run this command `pip install requirements.txt`
6. Instructions to type in commands to run the application. 

### TODO
- [x] Create Flask Hello World Site (Chapter 7)
- [x] Customize the site for our project
- [x] Generate `requirement.txt` file
- [x] Add instructions in the `Readme.md` file of our repo for the instructor

**Comment by richc117** [comment]
**Feedback from the professor**
Displaying the notification is the most important part. So how are we going to do that.

**Comment by richc117** [comment]
flask site was created on the site
